# Generated by Django 5.2.11 on 2026-08-26 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('slug', models.SlugField(editable=False, max_length=180, unique=True)),
                ('description', models.TextField(verbose_name='descripción')),
                ('prize', models.CharField(max_length=200, verbose_name='premio')),
                ('total_numbers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='cantidad de números')),
                ('number_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio por número')),
                ('draw_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha del sorteo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('closed', 'Cerrada')], default='draft', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL, verbose_name='organizador')),
            ],
            options={
                'verbose_name': 'rifa',
                'verbose_name_plural': 'rifas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaffleNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('pending', 'Pago pendiente'), ('sold', 'Vendido')], default='available', max_length=20, verbose_name='estado')),
                ('buyer_name', models.CharField(blank=True, max_length=150, verbose_name='comprador')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='correo del comprador')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'número de rifa',
                'verbose_name_plural': 'números de rifa',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('raffle', 'number'), name='unique_number_per_raffle')],
            },
        ),
    ]
