# Generated by Django 5.2.11 on 2026-08-27 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('buyer_name', models.CharField(max_length=150, verbose_name='nombre')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('confirmed', 'Confirmada'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(verbose_name='vence el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rafflenumber',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbers', to='raffles.reservation'),
        ),
    ]
