# Generated by Django 5.2.11 on 2026-08-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_reservation_rafflenumber_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='account_holder',
            field=models.CharField(blank=True, max_length=150, verbose_name='titular'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='account_holder_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT del titular'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='número de cuenta'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='tipo de cuenta'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='transfer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo para transferencias'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='comprobante'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='comprobante recibido'),
        ),
    ]
