# Generated by Django 5.2.11 on 2026-08-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_raffle_account_holder_raffle_account_holder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='raffle-covers/%Y/%m/', verbose_name='imagen de portada'),
        ),
    ]
