# Generated by Django 5.2.11 on 2026-08-27 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_raffle_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('drawn_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raffle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draw', to='raffles.raffle')),
                ('winning_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winning_draws', to='raffles.rafflenumber', verbose_name='número ganador')),
            ],
            options={
                'verbose_name': 'sorteo',
                'verbose_name_plural': 'sorteos',
            },
        ),
    ]
