# Generated by Django 5.2.11 on 2026-08-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_raffledraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_snapshot',
            field=models.JSONField(default=list, verbose_name='números reservados'),
        ),
    ]
